prepare to replace USDCe with USDC native

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -161,7 +161,10 @@ jobs:
           # ./utils/register.sh -a mainnet -u ${{ secrets.RPC_V9 }} -c 0x05F062C924EcD9f5d4C74c567A28cc5502332fcf21828687EC20581a03F7E1C8 -n DELEVERAGES -h ${DELEVERAGE_COMPONENT_HASH}
           # ./utils/register.sh -a mainnet -u ${{ secrets.RPC_V9 }} -c 0x05F062C924EcD9f5d4C74c567A28cc5502332fcf21828687EC20581a03F7E1C8 -n DEPOSITS -h ${DEPOSIT_COMPONENT_HASH}
           # ./utils/register.sh -a mainnet -u ${{ secrets.RPC_V9 }} -c 0x05F062C924EcD9f5d4C74c567A28cc5502332fcf21828687EC20581a03F7E1C8 -n ASSETS -h ${ASSET_MANAGER_COMPONENT_HASH}    
-          MIGRATE_USDC_EIC_HASH=$(./utils/declare.sh -a mainnet -u ${{ secrets.RPC_V9 }} -c MigrateTVLEIC -p perpetuals)
-          echo "MIGRATE_USDC_EIC_HASH=$MIGRATE_USDC_EIC_HASH"      
-          voyager verify --network mainnet --class-hash $MIGRATE_USDC_EIC_HASH --contract-name MigrateTVLEIC --license Apache-2.0  --package perpetuals --watch --lock-file  || echo "MigrateTVLEIC verification might have failed check https://voyager.online/class/$MIGRATE_USDC_EIC_HASH"   
-
+          REPLACE_COLLATERAL_VAULT_EIC_HASH=$(./utils/declare.sh -a mainnet -u ${{ secrets.RPC_V9 }} -c ReplaceCollateralVaultEIC -p perpetuals)
+          echo "REPLACE_COLLATERAL_VAULT_EIC_HASH=$REPLACE_COLLATERAL_VAULT_EIC_HASH"      
+          voyager verify --network mainnet --class-hash $REPLACE_COLLATERAL_VAULT_EIC_HASH --contract-name ReplaceCollateralVaultEIC --license Apache-2.0  --package perpetuals --watch --lock-file  || echo "ReplaceCollateralVaultEIC verification might have failed check https://voyager.online/class/$REPLACE_COLLATERAL_VAULT_EIC_HASH"   
+          
+          REPLACE_COLLATERAL_EIC_HASH=$(./utils/declare.sh -a mainnet -u ${{ secrets.RPC_V9 }} -c ReplaceCollateralEIC -p perpetuals)
+          echo "REPLACE_COLLATERAL_EIC_HASH=$REPLACE_COLLATERAL_EIC_HASH"      
+          voyager verify --network mainnet --class-hash $REPLACE_COLLATERAL_EIC_HASH --contract-name ReplaceCollateralEIC --license Apache-2.0  --package perpetuals --watch --lock-file  || echo "ReplaceCollateralEIC verification might have failed check https://voyager.online/class/$REPLACE_COLLATERAL_EIC_HASH" 
