deploy protocol vault

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -160,6 +160,6 @@ jobs:
           # ./utils/register.sh -a mainnet -u ${{ secrets.RPC_V9 }} -c 0x05F062C924EcD9f5d4C74c567A28cc5502332fcf21828687EC20581a03F7E1C8 -n DELEVERAGES -h ${DELEVERAGE_COMPONENT_HASH}
           # ./utils/register.sh -a mainnet -u ${{ secrets.RPC_V9 }} -c 0x05F062C924EcD9f5d4C74c567A28cc5502332fcf21828687EC20581a03F7E1C8 -n DEPOSITS -h ${DEPOSIT_COMPONENT_HASH}
           # ./utils/register.sh -a mainnet -u ${{ secrets.RPC_V9 }} -c 0x05F062C924EcD9f5d4C74c567A28cc5502332fcf21828687EC20581a03F7E1C8 -n ASSETS -h ${ASSET_MANAGER_COMPONENT_HASH}    
-          MIGRATE_COLLATERAL_TO_TREASURY_EIC_HASH=$(./utils/declare.sh -a mainnet -u ${{ secrets.RPC_V9 }} -c MigrateCollateralToTreasuryEIC -p perpetuals)
-          echo "MIGRATE_COLLATERAL_TO_TREASURY_EIC_HASH=$MIGRATE_COLLATERAL_TO_TREASURY_EIC_HASH"      
-          voyager verify --network mainnet --class-hash $MIGRATE_COLLATERAL_TO_TREASURY_EIC_HASH --contract-name MigrateCollateralToTreasuryEIC --license Apache-2.0  --package perpetuals --watch --lock-file  || echo "MigrateCollateralToTreasuryEIC verification might have failed check https://voyager.online/class/$MIGRATE_COLLATERAL_TO_TREASURY_EIC_HASH"
+          PROTOCOL_VAULT_HASH=$(./utils/declare.sh -a mainnet -u ${{ secrets.RPC_V9 }} -c ProtocolVault -p vault)
+          echo "PROTOCOL_VAULT_HASH=$PROTOCOL_VAULT_HASH"      
+          voyager verify --network mainnet --class-hash $PROTOCOL_VAULT_HASH --contract-name ProtocolVault --license Apache-2.0  --package vault --watch --lock-file  || echo "ProtocolVault verification might have failed check https://voyager.online/class/$PROTOCOL_VAULT_HASH"
